### PR TITLE
Support CUDA 11.x on ppc64le

### LINKED ISSUE #73: Build CUDA 11.x for ppc64le?
Currently we only build CUDA 10.2 on ppc64le:
https://github.com/conda-forge/nvcc-feedstock/blob/408c93112830bfbd8707ea5bc8a4be7cb6b94462/recipe/meta.yaml#L20
It looks like we have everything ready for removing this restriction?

### PR DESCRIPTION
**Pull request by leofang**
Close #73.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Note: I do not bump the build number because this is not a rebuild but simply an expansion of the build matrix.

**Comment by jakirkham** [comment]
Will need PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2001 )

**Comment by leofang** [comment]
@jakirkham Isn't it the other way around? That the migrator PR depends on this PR.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@jakirkham PTAL. I still think we need this PR to unblock anything else. To the very least, this would allow feedstock maintainers to opt in ppc64le support.

cc: @conda-forge/nvcc

**Comment by kkraus14** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Review by kkraus14 — APPROVED** [review]

**Comment by leofang** [comment]
Thanks, @kkraus14!

**Pull request merged**
