### PR TITLE
Add CUDA 11.7

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adds CUDA 11.7. Following the example of #77.

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Bradley! 🙏

CI failures are due to missing Docker images. PR ( https://github.com/conda-forge/docker-images/pull/214 ) will address this

**Comment by jakirkham** [comment]
Rerunning CI

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Some of the jobs failed on `main`. Though fixing required a re-render due to other issues. Addressed in PR ( https://github.com/conda-forge/nvcc-feedstock/pull/86 ) where CI now passes on `main`

**Pull request merged**
