### PR TITLE
expand matrix to cover 9.2-11.2

### PR DESCRIPTION
**Pull request by jaimergp**
MNT: Re-rendered with conda-build 3.20.5, conda-smithy 3.8.6, and conda-forge-pinning 2021.02.16.21.37.58

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

One of the premises for shrinking the CUDA matrix as part of https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1162 was that the maintainer could opt-in for more versions using `conda_build_config.yaml`. I have added what I think should be the full file (and that we will eventually link in the docs), but since `conda-smithy` applies the migrators _after_ `conda_build_config` it has no effect: the migrator shadows the changes.

Is this something we need to address in `conda-smithy`?

### CODE REVIEW

**Comment by isuruf** [comment]
You can just delete the other migrators.

**Comment by jaimergp** [comment]
That imply that users that need to opt-in would switch to a all-manual mode they need to take care of, right?

**Comment by jaimergp** [comment]
That implies that users that need to opt-in would switch to a all-manual mode they need to take care of, right?

**Comment by jaimergp** [comment]
That imply that users that need to opt-in would switch to a all-manual mode they need to take care of, right?

**Comment by jaimergp** [comment]
That implies that users that need to opt-in would switch to a all-manual mode they need to take care of, right?

**Comment by jaimergp** [comment]
Replacing the 11.1/11.2 migrator with the current `conda_build_config` (which contains more comments than usual) seems to work.

**Comment by isuruf** [comment]
> That implies that users that need to opt-in would switch to a all-manual mode they need to take care of, right?

Yes. I wouldn't worry about it being all-manual until a maintainer comes forward who says they need the older versions.

**Review by kkraus14 — APPROVED** [review]

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Jaime! 😄

**Pull request merged**
