### PR TITLE
Fix nvcc on Windows

### LINKED ISSUE #76: CMake cannot verify NVCC compiler after rerender to 2019 Windows Image
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
After a feedstock was [re-rendered to the 2019 Windows image](https://github.com/conda-forge/libastra-feedstock/pull/7), CMake can no longer verify NVCC as a working compiler. The version of the nvcc_win-64 is the same before and after the rerender. At first, I thought the problem was that the wrong host compiler was being assigned to NVCC because the version of the compiler linked to %CXX% did not match the host compiler reported by CMake, but then I also tried manually assigning NVCC and host compiler paths.

I really don't know what's going on.

<br/>
Environment (<code>conda list</code>):
<details>

```
    cmake:          3.21.3-h39d44d4_0       conda-forge
    ninja:          1.10.2-h2d74725_1       conda-forge
    nvcc_win-64:    11.2-h929061a_15        conda-forge
    ucrt:           10.0.20348.0-h57928b3_0 conda-forge
    vc:             14.2-hb210afc_5         conda-forge
    vs2015_runtime: 14.29.30037-h902a5da_5  conda-forge
    vs2017_win-64:  19.16.27038-h2e3bad8_2  conda-forge
    vswhere:        2.8.4-h57928b3_0        conda-forge


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by leofang**
Close #76.

The common symptom, likely triggered after the vs2019 update, is this error
```
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
```
We need to use the [`--use-local-env`](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-guiding-compiler-driver-use-local-env) flag to respect conda-forge's MSVC setup.
> Skip MSVC environment initialization.
> By default nvcc assumes that the MSVC environment needs to be initialized. This is done by executing the appropriate command file available for the MSVC installation detected or specified. Initializing the environment for each nvcc invocation can add noticeable overheads. If the environment used to invoke nvcc has already been configured, this option can be used to skip this step.

cc: @isuruf @carterbox

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
cc: @jaimergp

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Awesome!

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
0f50a2f is actually wrong, but the CI did not catch up, proving my suspicion https://github.com/conda-forge/nvcc-feedstock/issues/76#issuecomment-1172896089 is right...

**Comment by leofang** [comment]
I am trying to understand what's the difference between msvc in the build vs the test environment, because I am pretty sure the added flag is the solution for the building error (https://github.com/conda-forge/cupy-feedstock/pull/173/commits/b33baf470501c1c16f60e1210629de5a82fe903b).

**Comment by leofang** [comment]
> [0f50a2f](https://github.com/conda-forge/nvcc-feedstock/commit/0f50a2fd9be1ee4ff9ec87e2a6624d33cd2bb7c9) is actually wrong, but the CI did not catch it, proving my suspicion [#76 (comment)](https://github.com/conda-forge/nvcc-feedstock/issues/76#issuecomment-1172896089) is right...

And this is wrong 😑

**Comment by leofang** [comment]
My feeling is once we set `--use-local-env` we need to set all include and library search paths explicitly, which are done properly by any build system (setuptools, cmake, ...), but not in our simple test `nvcc test_nvcc.cu`.

**Comment by leofang** [comment]
> My feeling is once we set `--use-local-env` we need to set all include and library search paths explicitly, which are done properly by any build system (setuptools, cmake, ...), but not in our simple test `nvcc test_nvcc.cu`.

Perhaps we should only set this flag at the build stage...

**Comment by leofang** [comment]
@jakirkham @jaimergp any chance you guys know what's going on here?
```
(%PREFIX%) %SRC_DIR%>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc.exe" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" test.cu 
c:\program files\nvidia gpu computing toolkit\cuda\v11.7\include\crt/host_config.h(231): fatal error C1083: Cannot open include file: 'crtdefs.h': No such file or directory
test.cu
```

**Pull request closed without merging**
