### PR TITLE
Standalone (de)activate scripts; Early exit when outside conda-build environments 

### LINKED ISSUE #40: Install errors if CONDA_BUILD_SYSROOT is not defined.
<!--
Thanks for reporting your issue.
Please fill out the sections below.
-->
Issue:

The `nvcc-linux_64` install assumes a variable `CONDA_BUILD_SYSROOT` exists, but it does not on my setup (conda 4.8.4 with/without conda-build installed).

```console
$ conda install -c pytorch nvcc_linux-64                                               
Collecting package metadata (current_repodata.json): done                              
Solving environment: done                                                              
                                                                                       
                                                                                       
## Package Plan ##                                                                     
                                                                                       
  environment location: /dev/shm/envs/hello                                          
                                                                                       
  added / updated specs:                                                               
    - nvcc_linux-64                                                                    
                                                                                       
                                                                                       
The following packages will be downloaded:                                             
                                                                                       
    package                    |            build                                      
    ---------------------------|-----------------                                      
    nvcc_linux-64-10.2         |       hc6a2c23_6           7 KB  conda-forge          
    ------------------------------------------------------------                       
                                           Total:           7 KB                       
                                                                                       
The following NEW packages will be INSTALLED:                                          
                                                                                       
  nvcc_linux-64      conda-forge/linux-64::nvcc_linux-64-10.2-hc6a2c23_6               
                                                                                       
                                                                                       
Proceed ([y]/n)? y                                                                     
Downloading and Extracting Packages
nvcc_linux-64-10.2   | 7 KB      | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ln: failed to create symbolic link ‘/lib/libcuda.so’: Permission denied
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /dev/shm/envs/hello:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_tflow_select             2.3.0                       mkl
absl-py                   0.9.0                    py38_0
agate                     1.6.1                    py38_2
agate-dbf                 0.2.1                      py_0
agate-excel               0.2.3                      py_0
agate-sql                 0.5.4                      py_0
alembic                   1.4.2                      py_0
astropy                   4.0.1.post1      py38h7b6447c_1
astunparse                1.6.3                      py_0
attrs                     19.3.0                     py_0
autobahn                  20.7.1                     py_0    conda-forge
automat                   0.8.0                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
bcrypt                    3.1.7            py38h7b6447c_1
beautifulsoup4            4.9.1                    py38_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blinker                   1.4                      py38_0
bokeh                     2.1.1                    py38_0
brotlipy                  0.7.0           py38h7b6447c_1000
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.15.0            h7b6447c_1001
ca-certificates           2020.6.24                     0
cachetools                4.1.0                      py_1
cairo                     1.14.12              h8948797_3
catalogue                 1.0.0                    py38_1
certifi                   2020.6.20                py38_0
cffi                      1.14.0           py38h2e261b9_0
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
clickhouse-driver         0.1.4            py38h1e0a361_0    conda-forge
clickhouse-sqlalchemy     0.1.4                      py_0    conda-forge
cloudpickle               1.5.0                      py_0
conda                     4.8.4                    py38_0
conda-build               3.18.11                  py38_0
conda-package-handling    1.6.1            py38h7b6447c_0
configparser              5.0.0                      py_0
constantly                15.1.0                     py_0
coverage                  5.0              py38h7b6447c_0
croniter                  0.3.30                     py_0
cryptography              2.9.2            py38h1ba5d50_0
csvkit                    1.0.4                    py38_0
cvxopt                    1.2.0            py38hfa32c7d_0
cycler                    0.10.0                   py38_0
cymem                     2.0.3            py38he6710b0_0
cython-blis               0.4.1            py38h7b6447c_1
cytoolz                   0.10.1           py38h7b6447c_0
dask                      2.20.0                     py_0
dask-core                 2.20.0                     py_0
dbfread                   2.0.7                    py38_0
dbus                      1.13.16              hb2f20db_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
dill                      0.3.2                      py_0
distributed               2.20.0                   py38_0
dpkt                      1.9.3              pyh9f0ad1d_0    conda-forge
drmaa                     0.7.9                    py38_0
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
expat                     2.2.9                he6710b0_2
fastcache                 1.1.0            py38h7b6447c_0
filelock                  3.0.12                     py_0
flake8                    3.8.3                      py_0
flaky                     3.6.1                      py_0
flask                     1.1.2                      py_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.10.2               h5ab3b9f_0
fribidi                   1.0.9                h7b6447c_0
fsspec                    0.7.4                      py_0
future                    0.18.2                   py38_1
gast                      0.3.3                      py_0
gevent                    20.6.2           py38h7b6447c_0
glib                      2.63.1               h5a9c865_0
glob2                     0.7                        py_0
glpk                      4.65                 h3ceedfd_2
gmp                       6.1.2                h6c8ec71_1
gmpy2                     2.0.8            py38hd5f6e3b_3
google-auth               1.17.2                     py_0
google-auth-oauthlib      0.4.1                      py_2
google-pasta              0.2.0                      py_0
graphite2                 1.3.14               h23475e2_0
graphviz                  2.40.1               h21bd128_2
greenlet                  0.4.16           py38h7b6447c_0
grpcio                    1.27.2           py38hf8bcb03_0
gsl                       2.4                  h14c3975_4
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
h5py                      2.10.0           py38h7918eee_0
harfbuzz                  1.8.8                hffaf4a1_0
hdf5                      1.10.4               hb1b8bf9_0
heapdict                  1.0.1                      py_0
hyperlink                 19.0.0                     py_0
icu                       58.2                 he6710b0_3
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
incremental               17.5.0                   py38_0
influxdb                  5.3.0              pyh9f0ad1d_0    conda-forge
intel-openmp              2020.1                      217
ipdb                      0.13.0             pyh9f0ad1d_0    conda-forge
ipykernel                 5.3.3            py38h5ca1d4c_0
ipython                   7.16.1           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
isodate                   0.6.0                      py_1
itsdangerous              1.1.0                      py_0
jdcal                     1.4.1                      py_0
jedi                      0.17.1                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9b                   h024ee3a_2
json5                     0.9.5                      py_0
jsonschema                3.0.2                    py38_0
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
keras                     2.4.3                         0
keras-base                2.4.3                      py_0
keras-preprocessing       1.1.0                      py_1
kiwisolver                1.2.0            py38hfd86e86_0
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
leather                   0.3.3                    py38_0
libarchive                3.4.2                h62408e4_0
libedit                   3.1.20191231         h14c3975_1
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15                 h63c8f33_5
liblief                   0.10.1               he6710b0_0
libllvm9                  9.0.1                h4a3c616_1
libpng                    1.6.37               hbc83047_0
libprotobuf               3.12.3               hd408876_0
libsodium                 1.0.18               h7b6447c_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_1
libuuid                   1.0.3                h1bed415_2
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               he19cac6_1
libxslt                   1.1.34               hc22bd24_0
lightgbm                  2.3.0            py38he6710b0_0
line_profiler             2.1.2            py38h7b6447c_0
llvmlite                  0.33.0           py38hc6ec683_1
locket                    0.2.0                    py38_1
lxml                      4.5.2            py38hefd8a0e_0
lz4-c                     1.9.2                he6710b0_0
magma-cuda110             2.5.2                         1    pytorch
mako                      1.1.3                      py_0
markdown                  3.1.1                    py38_0
markupsafe                1.1.1            py38h7b6447c_0
matplotlib                3.2.2                         0
matplotlib-base           3.2.2            py38hef1b27d_0
mccabe                    0.6.1                    py38_1
metis                     5.1.0                hf484d3e_4
mistune                   0.8.4           py38h7b6447c_1000
mkl                       2020.1                      217
mkl-include               2020.1                      217
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.1.0            py38h23d657b_0
mkl_random                1.1.1            py38h0573a6f_0
mock                      4.0.2                      py_0
more-itertools            8.4.0                      py_0
mosek                     9.2.16                   py38_0    mosek
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpmath                    1.1.0                    py38_0
msgpack-python            1.0.0            py38hfd86e86_1
multi_key_dict            2.0.3                      py_0    conda-forge
murmurhash                1.0.2            py38he6710b0_0
mysql-connector-c         6.1.11               h597af5e_1
mysqlclient               2.0.1            py38he6710b0_0
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.7                      py_0
ncurses                   6.2                  he6710b0_1
networkx                  2.4                        py_1
ninja                     1.9.0            py38hfd86e86_0
notebook                  6.0.3                    py38_0
numba                     0.50.1           py38h0573a6f_1
numexpr                   2.7.1            py38h423224d_0
numpy                     1.18.5           py38ha1c710e_0
numpy-base                1.18.5           py38hde5b4d6_0
oauthlib                  3.1.0                      py_0
objgraph                  3.4.1              pyh9f0ad1d_0    conda-forge
olefile                   0.46                       py_0
openpyxl                  3.0.4                      py_0
openssl                   1.1.1g               h7b6447c_0
opt_einsum                3.1.0                      py_0
packaging                 20.4                       py_0
pandas                    1.0.5            py38h0573a6f_0
pandoc                    2.10                          0
pandocfilters             1.4.2                    py38_1
pango                     1.42.4               h049681c_0
paramiko                  2.7.1                      py_0
parse                     1.14.0                     py_0    conda-forge
parsedatetime             2.4                      py38_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
patchelf                  0.11                 he6710b0_0
patsy                     0.5.1                    py38_0
pcre                      8.44                 he6710b0_0
pexpect                   4.8.0                    py38_0
pickleshare               0.7.5                 py38_1000
pillow                    7.2.0            py38hb39fc2d_0
pip                       20.1.1                   py38_1
pixman                    0.40.0               h7b6447c_0
pkginfo                   1.5.0.1                  py38_0
plac                      0.9.6                    py38_1
plotly                    4.8.2                      py_0
pluggy                    0.13.1                   py38_0
preshed                   3.0.2            py38he6710b0_1
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
protobuf                  3.12.3           py38he6710b0_0
psutil                    5.7.0            py38h7b6447c_0
ptyprocess                0.6.0                    py38_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py38h403a769_0
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.7                      py_0
pybind11                  2.5.0            py38hfd86e86_0
pycodestyle               2.6.0                      py_0
pycosat                   0.6.3            py38h7b6447c_1
pycparser                 2.20                       py_2
pyflakes                  2.2.0                      py_0
pygments                  2.6.1                      py_0
pyhamcrest                2.0.2                      py_0
pyjwt                     1.7.1                    py38_0
pynacl                    1.4.0            py38h7b6447c_1
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py38h05f1152_4
pyrsistent                0.16.0           py38h7b6447c_0
pysocks                   1.7.1                    py38_0
pytest                    5.4.3                    py38_0
python                    3.8.2                hcf32534_0
python-dateutil           2.8.1                      py_0
python-editor             1.0.4                      py_0
python-jenkins            1.7.0                      py_0    conda-forge
python-libarchive-c       2.9                        py_0
python-slugify            3.0.4                      py_0
python_abi                3.8                      1_cp38    conda-forge
pytimeparse               1.1.8                    py38_0
pytz                      2020.1                     py_0
pywavelets                1.1.1            py38h7b6447c_0
pyyaml                    5.3.1            py38h7b6447c_1
pyzmq                     19.0.1           py38he6710b0_1
qt                        5.9.7                h5867ecd_1
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
readline                  8.0                  h7b6447c_0
redis-py                  3.5.3                      py_0
requests                  2.24.0                     py_0
requests-oauthlib         1.3.0                      py_0
retrying                  1.3.3                      py_2
ripgrep                   11.0.2               he32d670_0
rq                        1.2.2                      py_0    conda-forge
rsa                       4.0                        py_0
ruamel_yaml               0.15.87          py38h7b6447c_1
scikit-image              0.16.2           py38h0573a6f_0
scikit-learn              0.23.1           py38h423224d_0
scipy                     1.5.0            py38h0b6359f_0
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py38_0
service_identity          18.1.0                     py_0
setuptools                49.2.0                   py38_0
simplejson                3.17.0           py38h7b6447c_0
sip                       4.19.13          py38he6710b0_0
six                       1.15.0                     py_0
snakeviz                  2.0.1                    py38_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
spacy                     2.3.1            py38hfd86e86_0
sqlalchemy                1.3.18           py38h7b6447c_0
sqlite                    3.32.3               h62c20be_0
sqlparse                  0.3.1                      py_0
srsly                     1.0.2            py38he6710b0_0
statsmodels               0.11.1           py38h7b6447c_0
suitesparse               5.2.0                h9e4a6bb_0
sympy                     1.6.1                    py38_0
tabulate                  0.8.3                    py38_0
tbb                       2020.0               hfd86e86_0
tblib                     1.6.0                      py_0
tensorboard               2.2.1              pyh532a8cf_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorboardx              2.1                        py_0    conda-forge
tensorflow                2.2.0           mkl_py38h6d3daf0_0
tensorflow-base           2.2.0           mkl_py38h5059a2d_0
tensorflow-estimator      2.2.0              pyh208ff02_0
termcolor                 1.1.0                    py38_1
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
text-unidecode            1.3                        py_0
thinc                     7.4.1            py38hfd86e86_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               hbc83047_0
toolz                     0.10.0                     py_0
tornado                   6.0.4            py38h7b6447c_1
tqdm                      4.47.0                     py_0
traitlets                 4.3.3                    py38_0
twisted                   20.3.0           py38h7b6447c_0
txaio                     20.3.1                     py_0    conda-forge
typing_extensions         3.7.4.2                    py_0
tzlocal                   2.0.0                    py38_0
ujson                     3.0.0            py38he6710b0_0
unidecode                 1.1.1                      py_0
urllib3                   1.25.9                     py_0
voluptuous                0.11.7                     py_0    conda-forge
wasabi                    0.6.0                      py_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
websocket-client          0.57.0                   py38_1
werkzeug                  1.0.1                      py_0
wheel                     0.34.2                   py38_0
widgetsnbextension        3.5.1                    py38_0
wrapt                     1.12.1           py38h7b6447c_1
xarray                    0.16.0                     py_0
xlrd                      1.2.0                      py_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zeromq                    4.3.2                he6710b0_2
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h7b6447c_3
zope                      1.0                      py38_1
zope.event                4.4                      py38_0
zope.interface            4.7.1            py38h7b6447c_0
zstd                      1.4.5                h0b5b093_0
```
</details>



<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : /dev/shm/envs/hello                                                                                               
    active env location : /dev/shm/envs/hello                                                                                               
            shell level : 3                                                                                                                   
       user config file : /home/user/.condarc                                                                                             
 populated config files : /path/somewhere/miniconda3/.condarc                                                                               
                          /home/user/.condarc                                                                                             
          conda version : 4.8.3                                                                                                               
    conda-build version : not installed                                                                                                       
         python version : 3.7.6.final.0                                                                                                       
       virtual packages : __glibc=2.17                                                                                                        
       base environment : /path/somewhere/miniconda3  (read only)                                                                           
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64                                                                        
                          https://repo.anaconda.com/pkgs/main/noarch                                                                          
                          https://repo.anaconda.com/pkgs/r/linux-64                                                                           
                          https://repo.anaconda.com/pkgs/r/noarch                                                                             
                          https://conda.anaconda.org/conda-forge/linux-64                                                                     
                          https://conda.anaconda.org/conda-forge/noarch                                                                       
                          https://conda.anaconda.org/prometeia/linux-64                                                                       
                          https://conda.anaconda.org/prometeia/noarch                                                                         
                          https://conda.anaconda.org/mosek/linux-64                                                                           
                          https://conda.anaconda.org/mosek/noarch                                                                             
          package cache : /path/somewhere/miniconda3/pkgs                                                                                   
                          /home/user/.conda/pkgs                                                                                          
       envs directories : /path/somewhere/miniconda3/envs                                                                                   
                          /home/user/.conda/envs                                                                                          
               platform : linux-64                                                                                                            
             user-agent : conda/4.8.3 requests/2.23.0 CPython/X Linux/Y-stuff/Z glibc/W                
                UID:GID : 41652:40035                                                                                                         
             netrc file : None                                                                                                                
           offline mode : False                                                                                                               
```
</details>

### LINKED ISSUE #60: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### LINKED ISSUE #65: Error while installing nvcc on conda environment
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I receive the following error while trying to install nvcc in a conda environment.
`rm: cannot remove '/lib/libcuda.so': Permission denied
File /home/user/miniconda3/envs/tflow/lib/lib64/stubs/libcuda.so doesn't exist`

It seems that is trying to remove my system `/lib/libcuda.so` and I don't know why, plus this is undesirable behaviour as an end user I'll end up with a messed up system. 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /home/user/miniconda3/envs/tflow:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
anyio                     2.2.0            py37h06a4308_0
argon2-cffi               20.1.0           py37h27cfd23_1
async_generator           1.10             py37h28b3542_0
attrs                     20.3.0             pyhd3eb1b0_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
brotlipy                  0.7.0           py37h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.5           py37h261ae71_0
chardet                   4.0.0           py37h06a4308_1003
cite2c                    0.2.1                    pypi_0    pypi
cryptography              3.4.7            py37hd23ed53_0
cudatoolkit               10.2.89              hfd86e86_1
cycler                    0.10.0                   py37_0
dbus                      1.13.18              hb2f20db_0
decorator                 5.0.5              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
docstring-to-markdown     0.7                      pypi_0    pypi
entrypoints               0.3                      py37_0
expat                     2.3.0                h2531618_2
ffmpeg                    4.2.2                h20bf706_0
filelock                  3.0.12             pyhd3eb1b0_1
fontconfig                2.13.1               h6c09931_0
freetype                  2.10.4               h5ab3b9f_0                                                  [97/1845]
geomloss                  0.2.4                    pypi_0    pypi
glib                      2.68.0               h36276a3_0
gmp                       6.2.1                h2531618_2
gnutls                    3.6.5             h71b1129_1002
gpytorch                  1.3.1                    pypi_0    pypi
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
icu                       58.2                 he6710b0_3
idna                      2.10               pyhd3eb1b0_0
importlib-metadata        3.7.3            py37h06a4308_1
importlib_metadata        3.7.3                hd3eb1b0_1
intel-openmp              2020.2                      254
ipykernel                 5.3.4            py37h5ca1d4c_0
ipympl                    0.7.0              pyhd3eb1b0_0
ipython                   7.22.0           py37hb070fc8_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_1
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.3             pyhd3eb1b0_0
joblib                    1.0.1              pyhd3eb1b0_0
jpeg                      9b                   h024ee3a_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter-lsp               1.1.4              pyhd8ed1ab_0    conda-forge
jupyter-packaging         0.7.12             pyhd3eb1b0_0
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py37h06a4308_0
jupyter_server            1.4.1            py37h06a4308_0
jupyterlab                3.0.11             pyhd3eb1b0_1
jupyterlab-lsp            3.4.1              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.4.0              pyhd3eb1b0_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
kiwisolver                1.3.1            py37h2531618_0
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.33.1               h53a641e_7
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.18               h7b6447c_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_1                                                  [52/1845]
libuuid                   1.0.3                h1bed415_2
libuv                     1.40.0               h7b6447c_0
libvpx                    1.7.0                h439df22_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               hb55368b_3
lz4-c                     1.9.3                h2531618_0
markupsafe                1.1.1            py37h14c3975_1
matplotlib                3.3.4            py37h06a4308_0
matplotlib-base           3.3.4            py37h62a2d02_0
mistune                   0.8.4           py37h14c3975_1001
mkl                       2020.2                      256
mkl-service               2.3.0            py37he8ac12f_0
mkl_fft                   1.3.0            py37h54f3939_0
mkl_random                1.1.1            py37h0573a6f_0
nbclassic                 0.2.6              pyhd3eb1b0_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.1.3              pyhd3eb1b0_0
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.5.1              pyhd3eb1b0_0
nettle                    3.4.1                hbb512f6_0
ninja                     1.10.2           py37hff7bd54_0
nodejs                    10.13.0              he6710b0_0
notebook                  6.3.0            py37h06a4308_0
numpy                     1.19.2           py37h54aff64_0
numpy-base                1.19.2           py37hfa32c7d_0
nvcc_linux-64             10.2                h1a5f58c_12    conda-forge
olefile                   0.46                     py37_0
openh264                  2.1.0                hd408876_0
openssl                   1.1.1k               h27cfd23_0
packaging                 20.9               pyhd3eb1b0_0
pandas                    1.2.3            py37ha9443f7_0
pandoc                    2.12                 h06a4308_0
pandocfilters             1.4.3            py37h06a4308_1
parso                     0.7.1                    pypi_0    pypi
pcre                      8.44                 he6710b0_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.2.0            py37he98fc37_0
pip                       21.0.1           py37h06a4308_0
pluggy                    0.13.1                   pypi_0    pypi
prometheus_client         0.10.0             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyh06a4308_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pycparser                 2.20                       py_2                                                   [7/1845]
pygments                  2.8.1              pyhd3eb1b0_0
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.17.3           py37h7b6447c_0
pysocks                   1.7.1                    py37_1
python                    3.7.10               hdb3f193_0
python-dateutil           2.8.1              pyhd3eb1b0_0
python-jsonrpc-server     0.4.0                    pypi_0    pypi
python-language-server    0.36.2+49.g3536061          pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.8.1           py3.7_cuda10.2_cudnn7.6.5_0    pytorch
pytz                      2021.1             pyhd3eb1b0_0
pyzmq                     20.0.0           py37h2531618_1
qt                        5.9.7                h5867ecd_1
rauth                     0.7.3                    pypi_0    pypi
readline                  8.1                  h27cfd23_0
requests                  2.25.1             pyhd3eb1b0_0
scikit-learn              0.24.1           py37ha9443f7_0
scipy                     1.6.2            py37h91f5cce_0
seaborn                   0.11.1             pyhd3eb1b0_0
sed                       4.8                  he412f7d_0    conda-forge
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py37h06a4308_0
sip                       4.19.8           py37hf484d3e_0
six                       1.15.0           py37h06a4308_0
sniffio                   1.2.0            py37h06a4308_1
sqlite                    3.35.4               hdfb4753_0
terminado                 0.9.4            py37h06a4308_0
testpath                  0.4.4              pyhd3eb1b0_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               hbc83047_0
torchaudio                0.8.1                      py37    pytorch
torchvision               0.9.1                py37_cu102    pytorch
tornado                   6.1              py37h27cfd23_0
tqdm                      4.59.0             pyhd3eb1b0_1
traitlets                 5.0.5              pyhd3eb1b0_0
typing_extensions         3.7.4.3            pyha847dfd_0
ujson                     4.0.2                    pypi_0    pypi
urllib3                   1.26.4             pyhd3eb1b0_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py37_0
x264                      1!157.20191217       h7b6447c_0
xz                        5.2.5                h7b6447c_0
zeromq                    4.3.4                h2531618_0
zipp                      3.4.1              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.9                haebb681_0
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

   active environment : tflow
    active env location : /home/user/miniconda3/envs/tflow
            shell level : 1
       user config file : /home/user/.condarc
 populated config files :
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.2=0
                          __linux=4.14.225=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/user/miniconda3  (writable)
      conda av data dir : /home/user/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.7.10 Linux/4.14.225-1-MANJARO manjaro/21.0 glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by leofang**
Close #40, close #60, close #65.

This PR changes 3 things (following the commit order). Please pay particular attention to the 2nd one, as it would be a breaking change:
1. Make Linux activate/deactivate scripts standalone (which is already done for the Windows ones)
2. Prevent `nvcc` from being used outside conda-build envs (we call `rm -f` and we also rely on `CONDA_BUILD_SYSROOT`, so there is really not feasible for normal users to use)
3. Add myself as a maintianer

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
> Prevent nvcc from being used outside conda-build envs (we call rm -f and we also rely on CONDA_BUILD_SYSROOT, so there is really not feasible for normal users to use)

Why not? A user can simply do `conda create -n foo nvcc_linux-64 compilers`

**Comment by leofang** [comment]
> > Prevent nvcc from being used outside conda-build envs (we call rm -f and we also rely on CONDA_BUILD_SYSROOT, so there is really not feasible for normal users to use)
> 
> Why not? A user can simply do `conda create -n foo nvcc_linux-64 compilers`

I think it's better to discourage this, see #65.

**Comment by isuruf** [comment]
Can you change the condition then to check if `CONDA_BUILD_SYSROOT` is set?

**Review by kkraus14 — APPROVED** [review]

**Comment by leofang** [comment]
Superseded by #91.

**Pull request closed without merging**
